name: Android CI

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Wir wechseln mit 'working-directory' in den richtigen Ordner
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: android 

    - name: Build with Gradle
      run: ./gradlew assembleDebug
      working-directory: android

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        # Auch hier muss der Pfad angepasst werden
        path: android/app/build/outputs/apk/debug/app-debug.apk
